Using xgettext to extract the messages to translate

diff --git a/obrun.in b/obrun.in
--- a/obrun.in
+++ b/obrun.in
@@ -16,37 +16,42 @@ then
 fi
 install -d $XDG_CACHE_HOME $XDG_CONFIG_HOME $XDG_DATA_HOME
 
-show_error()
+export TEXTDOMAIN=obrun
+export TEXTDOMAINDIR=@prefix@/share/locale
+_()
 {
-    zenity --error --text="$1" || xmessage "$1" || echo "$1" >&2
+    which gettext >/dev/null 2>&1 && gettext "$@" || echo "$@"
 }
+
+for prog in gettext perl zenity;
+do
+    if ! which $prog >/dev/null 2>&1;
+    then
+        printf "`_ 'WARNING: %s not found. obrun may not work correctly.\n'`" "$prog" >&2
+    fi
+done
 
 show_dialog()
 {
     if test -f $XDG_CACHE_HOME/obrun.lock;
     then
-        show_error "`_ 'Another instance of obrun is already running'`"
+        _ 'Another instance of obrun is already running' >&2
         exit
     fi
     touch $XDG_CACHE_HOME/obrun.lock
 
-    if which zenity >/dev/null 2>&1;
-    then
-        local prog=$(cat $histfile | xargs zenity --title "`_ 'Run…'`" --text "`_ 'Select or enter a program to run'`" --height `get_setting height 60` --width `get_setting width 80` --`get_setting type` `get_setting arguments`)
-        exitcode=$?
+    local prog=$(cat $histfile | xargs zenity --title "`_ 'Run…'`" --text "`_ 'Select or enter a program to run'`" --height `get_setting height 60` --width `get_setting width 80` --`get_setting type` `get_setting arguments`)
+    exitcode=$?
 
-        # OK
-        if test $exitcode -eq 0;
+    # OK
+    if test $exitcode -eq 0;
+    then
+        if test "$command" == "remove";
         then
-            if test "$command" == "remove";
-            then
-                remove_entry "$prog"
-            else
-                add_entry "$prog"
-            fi
+            remove_entry "$prog"
+        else
+            add_entry "$prog"
         fi
-    else
-        show_error "`_ 'zenity not found'`"
     fi
     rm -f $XDG_CACHE_HOME/obrun.lock
     exit $exitcode
@@ -73,11 +78,6 @@ add_entry()
 remove_entry()
 {
     entry=$1
-    if ! which perl >/dev/null 2>&1;
-    then
-        show_error "`_ 'Can'\'t' remove the entry without perl'`"
-    fi
-
     perl -e '$m=`cat '$histfile'`; $m=~s/'$entry'\n//; print $m;' > $XDG_CACHE_HOME/.tmp
     if test $? -eq 0;
     then
@@ -85,38 +85,25 @@ remove_entry()
     fi
 }
 
-export TEXTDOMAIN=obrun
-export TEXTDOMAINDIR=@prefix@/share/locale
-_()
-{
-    which gettext >/dev/null 2>&1 && gettext -s "$@" || echo "$@"
-}
-
 get_setting()
 {
     setting=$1
     default=$2
     lines=`wc -l "$histfile" | cut -d ' ' -f 1`
-    if which xmllint > /dev/null 2>&1;
+    e=`xmllint --xpath "obrun_config/dialog/$setting$lines/text()" "$configfile"`
+    if test $? -eq 0;
     then
-        e=`xmllint --xpath "obrun_config/dialog/$setting$lines/text()" "$configfile"`
+        echo $e
+    else
+        e=`xmllint --xpath "obrun_config/dialog/$setting/text()" "$configfile"`
         if test $? -eq 0;
         then
             echo $e
         else
-            e=`xmllint --xpath "obrun_config/dialog/$setting/text()" "$configfile"`
-            if test $? -eq 0;
-            then
-                echo $e
-            else
-                echo $default
-            fi
+            echo $default
         fi
-    else
-        show_error "`_ 'xmllint not found. Can not read settings'`"
     fi
 }
-
 
 create_config()
 {
